server:
  port: ${PORT:8081}
logging:
  level:
    root: debug
spring:

  application:
    name: food

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/orders?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PWD:admin123}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true

  h2:
    console.enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE
