apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
   DB_URL: "amRiYzpteXNxbDovL215c3FsOjMzMDgvb3JkZXJzP2NyZWF0ZURhdGFiYXNlSWZOb3RFeGlzdD10cnVlJnVzZVNTTD1mYWxzZSZzZXJ2ZXJUaW1lem9uZT1VVEMmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZQ=="
   DB_USER: "ZG9ja2Vy"
   DB_PWD: "YWRtaW4xMjM="
   PORT: "ODA4OQ=="
